[phases.setup]
nixPkgs = ["python3", "chromium", "chromedriver"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "python3 start_app.py"
